/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, FunctionResult, BamlCtxManager, ClientRegistry, Image, Audio, Pdf, Video, FunctionLog,
HTTPRequest } from "@boundaryml/baml"
import { toBamlError, BamlStream, BamlAbortError, Collector } from "@boundaryml/baml"
import type { Checked, Check, RecursivePartialNull as MovedRecursivePartialNull } from "./types"
import type { partial_types } from "./partial_types"
import type * as types from "./types"
import type {CalculationResult, InvestorResponse, Message, NeedCalculation, NeedMoreInfo, NeedMoreResearch, NeedResearch, PythonCode, ResearchComplete, SearchQuery} from "./types"
import type TypeBuilder from "./type_builder"
import { AsyncHttpRequest, AsyncHttpStreamRequest } from "./async_request"
import { LlmResponseParser, LlmStreamParser } from "./parser"
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX,
DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"
import type * as events from "./events"

/**
* @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
*/
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>

    type TickReason = "Unknown";

    type BamlCallOptions<WatchersT = never> = {
    tb?: TypeBuilder
    clientRegistry?: ClientRegistry
    collector?: Collector | Collector[]
    env?: Record<string, string | undefined>
      tags?: Record<string, string>
        signal?: AbortSignal
        onTick?: (reason: TickReason, log: FunctionLog | null) => void
        watchers?: WatchersT
        }

        export class BamlAsyncClient {
        private runtime: BamlRuntime
        private ctxManager: BamlCtxManager
        private streamClient: BamlStreamClient
        private httpRequest: AsyncHttpRequest
        private httpStreamRequest: AsyncHttpStreamRequest
        private llmResponseParser: LlmResponseParser
        private llmStreamParser: LlmStreamParser
        private bamlOptions: BamlCallOptions

        constructor(runtime: BamlRuntime, ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
        this.runtime = runtime
        this.ctxManager = ctxManager
        this.streamClient = new BamlStreamClient(runtime, ctxManager, bamlOptions)
        this.httpRequest = new AsyncHttpRequest(runtime, ctxManager)
        this.httpStreamRequest = new AsyncHttpStreamRequest(runtime, ctxManager)
        this.llmResponseParser = new LlmResponseParser(runtime, ctxManager)
        this.llmStreamParser = new LlmStreamParser(runtime, ctxManager)
        this.bamlOptions = bamlOptions || {}
        }

        withOptions(bamlOptions: BamlCallOptions) {
        return new BamlAsyncClient(this.runtime, this.ctxManager, bamlOptions)
        }

        get stream() {
        return this.streamClient
        }

        get request() {
        return this.httpRequest
        }

        get streamRequest() {
        return this.httpStreamRequest
        }

        get parse() {
        return this.llmResponseParser
        }

        get parseStream() {
        return this.llmStreamParser
        }

        
        async InvestorAgent(
        messages: types.Message[],research_results?: string | null,calculation_results?: string | null,planning_steps?: string | null,current_date: string,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.InvestorResponse | types.NeedResearch | types.NeedCalculation | types.NeedMoreInfo> {
          try {
          const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const signal = options.signal;

          if (signal?.aborted) {
          throw new BamlAbortError('Operation was aborted', signal.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (options.onTick) {
          const stream = this.stream.InvestorAgent(
          messages,research_results,calculation_results,planning_steps,current_date,
          __baml_options__
          );

          return await stream.getFinalResponse();
          }

          const collector = options.collector ? (Array.isArray(options.collector) ? options.collector :
          [options.collector]) : [];
          const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const env: Record<string, string> = Object.fromEntries(
            Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const raw = await this.runtime.callFunction(
            "InvestorAgent",
            {
            "messages": messages,"research_results": research_results?? null,"calculation_results": calculation_results?? null,"planning_steps": planning_steps?? null,"current_date": current_date
            },
            this.ctxManager.cloneContext(),
            options.tb?.__tb(),
            options.clientRegistry,
            collector,
            options.tags || {},
            env,
            signal,
            options.watchers,
            )
            return raw.parsed(false) as types.InvestorResponse | types.NeedResearch | types.NeedCalculation | types.NeedMoreInfo
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async PythonCalculator(
        request: string,python_code_response?: string | null,previous_plannification_steps?: string | null,previous_python_code?: string | null,iteration_count: number,max_iterations: number,current_date: string,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.PythonCode | types.CalculationResult> {
          try {
          const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const signal = options.signal;

          if (signal?.aborted) {
          throw new BamlAbortError('Operation was aborted', signal.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (options.onTick) {
          const stream = this.stream.PythonCalculator(
          request,python_code_response,previous_plannification_steps,previous_python_code,iteration_count,max_iterations,current_date,
          __baml_options__
          );

          return await stream.getFinalResponse();
          }

          const collector = options.collector ? (Array.isArray(options.collector) ? options.collector :
          [options.collector]) : [];
          const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const env: Record<string, string> = Object.fromEntries(
            Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const raw = await this.runtime.callFunction(
            "PythonCalculator",
            {
            "request": request,"python_code_response": python_code_response?? null,"previous_plannification_steps": previous_plannification_steps?? null,"previous_python_code": previous_python_code?? null,"iteration_count": iteration_count,"max_iterations": max_iterations,"current_date": current_date
            },
            this.ctxManager.cloneContext(),
            options.tb?.__tb(),
            options.clientRegistry,
            collector,
            options.tags || {},
            env,
            signal,
            options.watchers,
            )
            return raw.parsed(false) as types.PythonCode | types.CalculationResult
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async WebResearcher(
        original_query: string,previous_results?: string | null,new_search_results?: string | null,planning_steps?: string | null,iteration_count: number,max_iterations: number,current_date: string,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.SearchQuery | types.ResearchComplete | types.NeedMoreResearch> {
          try {
          const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const signal = options.signal;

          if (signal?.aborted) {
          throw new BamlAbortError('Operation was aborted', signal.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (options.onTick) {
          const stream = this.stream.WebResearcher(
          original_query,previous_results,new_search_results,planning_steps,iteration_count,max_iterations,current_date,
          __baml_options__
          );

          return await stream.getFinalResponse();
          }

          const collector = options.collector ? (Array.isArray(options.collector) ? options.collector :
          [options.collector]) : [];
          const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const env: Record<string, string> = Object.fromEntries(
            Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const raw = await this.runtime.callFunction(
            "WebResearcher",
            {
            "original_query": original_query,"previous_results": previous_results?? null,"new_search_results": new_search_results?? null,"planning_steps": planning_steps?? null,"iteration_count": iteration_count,"max_iterations": max_iterations,"current_date": current_date
            },
            this.ctxManager.cloneContext(),
            options.tb?.__tb(),
            options.clientRegistry,
            collector,
            options.tags || {},
            env,
            signal,
            options.watchers,
            )
            return raw.parsed(false) as types.SearchQuery | types.ResearchComplete | types.NeedMoreResearch
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
            }

            class BamlStreamClient {
            private runtime: BamlRuntime
            private ctxManager: BamlCtxManager
            private bamlOptions: BamlCallOptions

            constructor(runtime: BamlRuntime, ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
            this.runtime = runtime
            this.ctxManager = ctxManager
            this.bamlOptions = bamlOptions || {}
            }

            
            InvestorAgent(
            messages: types.Message[],research_results?: string | null,calculation_results?: string | null,planning_steps?: string | null,current_date: string,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.InvestorResponse | partial_types.NeedResearch | partial_types.NeedCalculation | partial_types.NeedMoreInfo, types.InvestorResponse | types.NeedResearch | types.NeedCalculation | types.NeedMoreInfo>
              {
              try {
              const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const signal = options.signal;

              if (signal?.aborted) {
              throw new BamlAbortError('Operation was aborted', signal.reason);
              }

              let collector = options.collector ? (Array.isArray(options.collector) ? options.collector :
              [options.collector]) : [];

              let onTickWrapper: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (options.onTick) {
              const tickCollector = new Collector("on-tick-collector");
              collector = [...collector, tickCollector];

              onTickWrapper = () => {
              const log = tickCollector.last;
              if (log) {
              try {
              options.onTick!("Unknown", log);
              } catch (error) {
              console.error("Error in onTick callback for InvestorAgent", error);
              }
              }
              };
              }

              const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const env: Record<string, string> = Object.fromEntries(
                Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const raw = this.runtime.streamFunction(
                "InvestorAgent",
                {
                "messages": messages,"research_results": research_results ?? null,"calculation_results": calculation_results ?? null,"planning_steps": planning_steps ?? null,"current_date": current_date
                },
                undefined,
                this.ctxManager.cloneContext(),
                options.tb?.__tb(),
                options.clientRegistry,
                collector,
                options.tags || {},
                env,
                signal,
                onTickWrapper,
                )
                return new BamlStream<partial_types.InvestorResponse | partial_types.NeedResearch | partial_types.NeedCalculation | partial_types.NeedMoreInfo, types.InvestorResponse | types.NeedResearch | types.NeedCalculation | types.NeedMoreInfo>(
                  raw,
                  (a): partial_types.InvestorResponse | partial_types.NeedResearch | partial_types.NeedCalculation | partial_types.NeedMoreInfo => a,
                  (a): types.InvestorResponse | types.NeedResearch | types.NeedCalculation | types.NeedMoreInfo => a,
                  this.ctxManager.cloneContext(),
                  options.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            PythonCalculator(
            request: string,python_code_response?: string | null,previous_plannification_steps?: string | null,previous_python_code?: string | null,iteration_count: number,max_iterations: number,current_date: string,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.PythonCode | partial_types.CalculationResult, types.PythonCode | types.CalculationResult>
              {
              try {
              const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const signal = options.signal;

              if (signal?.aborted) {
              throw new BamlAbortError('Operation was aborted', signal.reason);
              }

              let collector = options.collector ? (Array.isArray(options.collector) ? options.collector :
              [options.collector]) : [];

              let onTickWrapper: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (options.onTick) {
              const tickCollector = new Collector("on-tick-collector");
              collector = [...collector, tickCollector];

              onTickWrapper = () => {
              const log = tickCollector.last;
              if (log) {
              try {
              options.onTick!("Unknown", log);
              } catch (error) {
              console.error("Error in onTick callback for PythonCalculator", error);
              }
              }
              };
              }

              const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const env: Record<string, string> = Object.fromEntries(
                Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const raw = this.runtime.streamFunction(
                "PythonCalculator",
                {
                "request": request,"python_code_response": python_code_response ?? null,"previous_plannification_steps": previous_plannification_steps ?? null,"previous_python_code": previous_python_code ?? null,"iteration_count": iteration_count,"max_iterations": max_iterations,"current_date": current_date
                },
                undefined,
                this.ctxManager.cloneContext(),
                options.tb?.__tb(),
                options.clientRegistry,
                collector,
                options.tags || {},
                env,
                signal,
                onTickWrapper,
                )
                return new BamlStream<partial_types.PythonCode | partial_types.CalculationResult, types.PythonCode | types.CalculationResult>(
                  raw,
                  (a): partial_types.PythonCode | partial_types.CalculationResult => a,
                  (a): types.PythonCode | types.CalculationResult => a,
                  this.ctxManager.cloneContext(),
                  options.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            WebResearcher(
            original_query: string,previous_results?: string | null,new_search_results?: string | null,planning_steps?: string | null,iteration_count: number,max_iterations: number,current_date: string,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.SearchQuery | partial_types.ResearchComplete | partial_types.NeedMoreResearch, types.SearchQuery | types.ResearchComplete | types.NeedMoreResearch>
              {
              try {
              const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const signal = options.signal;

              if (signal?.aborted) {
              throw new BamlAbortError('Operation was aborted', signal.reason);
              }

              let collector = options.collector ? (Array.isArray(options.collector) ? options.collector :
              [options.collector]) : [];

              let onTickWrapper: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (options.onTick) {
              const tickCollector = new Collector("on-tick-collector");
              collector = [...collector, tickCollector];

              onTickWrapper = () => {
              const log = tickCollector.last;
              if (log) {
              try {
              options.onTick!("Unknown", log);
              } catch (error) {
              console.error("Error in onTick callback for WebResearcher", error);
              }
              }
              };
              }

              const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const env: Record<string, string> = Object.fromEntries(
                Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const raw = this.runtime.streamFunction(
                "WebResearcher",
                {
                "original_query": original_query,"previous_results": previous_results ?? null,"new_search_results": new_search_results ?? null,"planning_steps": planning_steps ?? null,"iteration_count": iteration_count,"max_iterations": max_iterations,"current_date": current_date
                },
                undefined,
                this.ctxManager.cloneContext(),
                options.tb?.__tb(),
                options.clientRegistry,
                collector,
                options.tags || {},
                env,
                signal,
                onTickWrapper,
                )
                return new BamlStream<partial_types.SearchQuery | partial_types.ResearchComplete | partial_types.NeedMoreResearch, types.SearchQuery | types.ResearchComplete | types.NeedMoreResearch>(
                  raw,
                  (a): partial_types.SearchQuery | partial_types.ResearchComplete | partial_types.NeedMoreResearch => a,
                  (a): types.SearchQuery | types.ResearchComplete | types.NeedMoreResearch => a,
                  this.ctxManager.cloneContext(),
                  options.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
                  }

                  export const b = new BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
                  DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)