/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio, Pdf, Video } from "@boundaryml/baml"
import { toBamlError, HTTPRequest } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {CalculationResult, InvestorResponse, Message, NeedCalculation, NeedMoreInfo, NeedMoreResearch, NeedResearch, PythonCode, ResearchComplete, SearchQuery} from "./types"
import type TypeBuilder from "./type_builder"
import type * as events from "./events"

type BamlCallOptions<EventsT = never> = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
  env?: Record<string, string | undefined>
  events?: EventsT
}

export class HttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  InvestorAgent(
      messages: types.Message[],research_results?: string | null,calculation_results?: string | null,planning_steps?: string | null,current_date: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "InvestorAgent",
        {
          "messages": messages,"research_results": research_results?? null,"calculation_results": calculation_results?? null,"planning_steps": planning_steps?? null,"current_date": current_date
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  PythonCalculator(
      request: string,python_code_response?: string | null,previous_plannification_steps?: string | null,previous_python_code?: string | null,iteration_count: number,max_iterations: number,current_date: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "PythonCalculator",
        {
          "request": request,"python_code_response": python_code_response?? null,"previous_plannification_steps": previous_plannification_steps?? null,"previous_python_code": previous_python_code?? null,"iteration_count": iteration_count,"max_iterations": max_iterations,"current_date": current_date
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  WebResearcher(
      original_query: string,previous_results?: string | null,new_search_results?: string | null,planning_steps?: string | null,iteration_count: number,max_iterations: number,current_date: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "WebResearcher",
        {
          "original_query": original_query,"previous_results": previous_results?? null,"new_search_results": new_search_results?? null,"planning_steps": planning_steps?? null,"iteration_count": iteration_count,"max_iterations": max_iterations,"current_date": current_date
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class HttpStreamRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  InvestorAgent(
      messages: types.Message[],research_results?: string | null,calculation_results?: string | null,planning_steps?: string | null,current_date: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "InvestorAgent",
        {
          "messages": messages,"research_results": research_results?? null,"calculation_results": calculation_results?? null,"planning_steps": planning_steps?? null,"current_date": current_date
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  PythonCalculator(
      request: string,python_code_response?: string | null,previous_plannification_steps?: string | null,previous_python_code?: string | null,iteration_count: number,max_iterations: number,current_date: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "PythonCalculator",
        {
          "request": request,"python_code_response": python_code_response?? null,"previous_plannification_steps": previous_plannification_steps?? null,"previous_python_code": previous_python_code?? null,"iteration_count": iteration_count,"max_iterations": max_iterations,"current_date": current_date
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  WebResearcher(
      original_query: string,previous_results?: string | null,new_search_results?: string | null,planning_steps?: string | null,iteration_count: number,max_iterations: number,current_date: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "WebResearcher",
        {
          "original_query": original_query,"previous_results": previous_results?? null,"new_search_results": new_search_results?? null,"planning_steps": planning_steps?? null,"iteration_count": iteration_count,"max_iterations": max_iterations,"current_date": current_date
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}